"""Step 29 — generates KAGGLE/step29_test_eval/kaggle_step29_test_eval.ipynb from
scripts/run_test_eval.py.

Same discipline as scripts/build_kaggle_notebook.py (Step 28): the notebook is generated
from the real repo file, never hand-edited on kaggle.com, so the two can't drift apart.
Change scripts/run_test_eval.py, then:

    python scripts/build_kaggle_notebook_step29.py

and push the regenerated notebook (`kaggle kernels push -p KAGGLE/step29_test_eval/`).

**v2 (2026-08-13): adds the region-routing hybrid pass** (plan.md Step 29's 2026-08-13
update, Step 28 point 11) -- a deliberate SECOND TEST-set measurement, on top of the
original baseline + curve_n122 (`finetuned`) pair v1 already produced. `run_finetune.py`
and `KAGGLE/region_routing_check/validate_region_routing.py` (the hybrid's reference
implementation) are both already merged to `main` (Steps 27/28), so only
`scripts/run_test_eval.py` itself needs embedding here -- unlike Step 28's own notebook,
which had to embed five files because it touched shared pipeline code.

Runs baseline + finetuned + hybrid all in ONE clean push rather than trying to seed v1's
already-committed results into a fresh Kaggle clone (which doesn't have them -- they're
local/PR-pending, not on `main` yet): simpler and fully self-contained ("reproducible from
a notebook cell", plan.md's own Step 29 bar), at the cost of ~20-30 min of redone GPU time
for baseline+finetuned. All three phases are independently resumable (`run()`/
`run_hybrid()`'s own per-page checkpointing), so a re-push after an interruption picks up
where it left off rather than restarting.

Local CPU run of v1 (baseline+finetuned only) measured ~250s/page -- Kaggle's T4 GPU
(Step 16's own measured 17.4s/page) brings the whole run under an hour even with the
hybrid pass added, and Kaggle's environment doesn't have the page-file ceiling that forced
the two-phase split locally for baseline vs. finetuned (a T4 has 16GB, both models fit
easily) -- kept as separate cells for output-size/readability, not because GPU memory
requires it.
"""

from __future__ import annotations

import json
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SCRIPT = (REPO_ROOT / "scripts" / "run_test_eval.py").read_text(encoding="utf-8")

OWNER = "himadribiswas0904"
KERNEL_SLUG = "mathscholar-step29-test-eval"
REPO_URL = "https://github.com/anuronmaitro/doc-agent-1.git"


def md(src: str) -> dict:
    return {"cell_type": "markdown", "metadata": {}, "source": src.splitlines(keepends=True)}


def code(src: str) -> dict:
    return {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": src.splitlines(keepends=True),
    }


def build_cells() -> list[dict]:
    cells: list[dict] = []

    cells.append(
        md("""# MathScholar (team 1) — Step 29: final TEST measurement (run TWICE, deliberately)

Owner: Himadri Gobinda Biswas (S2, 2105047).

Runs `plan.md` Step 29 over the 39 TEST pages in `grading_kit/labels.jsonl` — **three**
readers this time:
1. **baseline** — pretrained `facebook/nougat-base`.
2. **finetuned** — base + `data/models/ocr_lora/curve_n122` LoRA adapter. The ORIGINAL,
   one-time Step 29 measurement.
3. **hybrid** — the **region-routing hybrid** added at Step 28 point 11 (`curve_n122`
   whole-page generation + `table_ft` applied only to detected table-region crops).
   Validated on the 20 VAL pages only (never touched TEST) before now: failure_rate=0.05
   vs 0.10 for either adapter alone. This is a **SECOND, deliberate TEST-set measurement**
   — a known deviation from Step 29's own "one-time opening" rule, decided explicitly by
   the team (plan.md's 2026-08-13 update) to evaluate a reader that only had validation
   evidence. Report BOTH #2 and #3 in the final table — append, don't replace.

**Do not edit this notebook directly on kaggle.com and expect it to survive** — it is
generated by `scripts/build_kaggle_notebook_step29.py` from `scripts/run_test_eval.py`.
Change the repo file and regenerate, so the two never drift apart.

**Why this runs on Kaggle at all** (Step 29 doesn't strictly require a GPU per plan.md):
a local CPU run of baseline+finetuned alone measured ~250s/page, and two full models
can't even share memory at once locally (a page-file crash, see the PR description) — a
free Kaggle T4 makes the full three-reader run well under an hour with no local resource
risk.
""")
    )

    cells.append(code(f"""REPO_URL = "{REPO_URL}"
BRANCH = "main"   # curve_n122 adapter, grading_kit/labels.jsonl + heldout_pages/ are all
                   # already committed on main -- nothing to materialize separately.
"""))

    cells.append(md("""## 1. Clone the repo and install pinned dependencies

`main` already has everything this step needs: the fine-tuned adapters
(`data/models/ocr_lora/{curve_n122,table_ft}/`, Step 28), the region-routing hybrid's
reference implementation (`KAGGLE/region_routing_check/validate_region_routing.py` +
`scripts/run_finetune.py`, both merged at Step 28 point 11), and the 39 TEST pages
(`grading_kit/labels.jsonl` + `grading_kit/heldout_pages/*.png`, committed since Step 20).
It does **not** have `scripts/run_test_eval.py` yet (this step's own deliverable, still on
Himadri's local branch) — embedded in the next cell."""))

    cells.append(code("""import os
import subprocess

if not os.path.exists("/kaggle/working/repo"):
    subprocess.run(["git", "clone", "--branch", BRANCH, "--depth", "1", REPO_URL, "/kaggle/working/repo"], check=True)
%cd /kaggle/working/repo
!git log --oneline -3
"""))

    cells.append(code("""!pip install -q --no-cache-dir -r requirements.lock
import pkg_resources  # noqa: F401
import torch

print("pkg_resources OK")
print("CUDA available:", torch.cuda.is_available())
"""))

    cells.append(md("""## 2. Write `scripts/run_test_eval.py`

One file embedded verbatim (it only imports `doc_agent.eval.metrics` and
`doc_agent.vision.ocr`, both unchanged from `main` by this step, so nothing else needs
embedding — unlike Step 28, which had to embed five files because it touched shared
pipeline code)."""))

    cells.append(code("%%writefile scripts/run_test_eval.py\n" + SCRIPT))

    cells.append(md("""## 3. Timing probe (measure before committing to the full 39 pages)

`plan.md`'s own recurring instruction: don't assume a number, measure it. Runs the
baseline reader on 2 pages first so a GPU-time estimate is real, not guessed."""))

    cells.append(code("""import time

t0 = time.time()
!python scripts/run_test_eval.py --run baseline --limit 2
elapsed = time.time() - t0
print(f"\\n{elapsed:.1f}s for 2 pages -> ~{elapsed/2:.1f}s/page -> "
      f"~{elapsed/2*78/60:.1f} min estimated for baseline+finetuned's 78 generations "
      f"(39 pages x 2 readers -- the hybrid pass in section 6 is additional, variable cost "
      f"on top of this, since it only re-generates on failed/table-region pages)")
"""))

    cells.append(md("""## 4. Baseline — all 39 TEST pages

Resumable: re-running this cell skips pages already scored in
`reports/step29_test_eval_results.json` (unless a fresh `--limit` truncated it above —
this cell reruns the 2 timing-probe pages plus the remaining 37 either way, real
generations, not reused stub data)."""))

    cells.append(code("!python scripts/run_test_eval.py --run baseline\n"))

    cells.append(
        md("""## 5. Fine-tuned (`curve_n122`) — all 39 TEST pages — the ORIGINAL Step 29 measurement

Same resumability. Loaded as a fresh process cell-to-cell on Kaggle too (simpler to keep
identical to the local two-phase script rather than add a GPU-only combined path just to
save the ~10s extra model-load time).""")
    )

    cells.append(code("!python scripts/run_test_eval.py --run finetuned\n"))

    cells.append(
        md(
            """## 6. Region-routing hybrid — all 39 TEST pages — the SECOND, deliberate TEST-set measurement

`curve_n122` whole-page generation (reused from section 5's results, not regenerated) +
`table_ft` applied only to detected table-region crops
(`KAGGLE/region_routing_check/validate_region_routing.py`'s `build_hybrid_prediction()`,
which already has 2 real splice bugs fixed — see its module docstring). Requires section 5
to have completed first (`run_hybrid()` reads "finetuned" from the results file rather
than re-generating it). Cost is variable, not a flat per-page rate: `table_ft` is only
called for (a) a whole-page fallback on pages where `curve_n122` already failed, and
(b) crop-level generation on pages `layout.detect()` finds a table region on — so this
cell's wall-clock time depends on how many of the 39 pages hit either case, not 39 x a
fixed cost."""
        )
    )

    cells.append(code("!python scripts/run_test_eval.py --run hybrid\n"))

    cells.append(md("""## 7. Build the report

Before/after table (failure rate, char-F1, exact-match) for baseline, `curve_n122`, AND
the region-routing hybrid side by side, per-page-type breakdown, worst failure for both
fine-tuned readers, and the sanity check against `summary.md` §4e's expected bands."""))

    cells.append(code("!python scripts/run_test_eval.py --report\n"))

    cells.append(md("""## 8. Package the output for download

Two files: the raw per-page results (full `pred_text` for all three readers on all 39
pages — re-scorable later without regenerating anything, same discipline as Step 28's
`run_state.json`) and the human-readable report."""))

    cells.append(code("""import shutil

out_dir = "/kaggle/working/out"
os.makedirs(out_dir, exist_ok=True)
shutil.copy("reports/step29_test_eval_results.json", out_dir)
shutil.copy("reports/step29_test_eval.md", out_dir)

archive_path = shutil.make_archive("/kaggle/working/step29_output", "zip", out_dir)
print(f"wrote {archive_path} ({os.path.getsize(archive_path) / 1e6:.1f} MB)")
print()
print("Download: notebook right sidebar -> Output -> step29_output.zip")
print("Unzip into the repo at reports/ -- see the PR description for the commit sequence.")
"""))

    return cells


def main() -> None:
    cells = build_cells()
    nb = {
        "cells": cells,
        "metadata": {
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python", "version": "3.10"},
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }
    out_dir = REPO_ROOT / "KAGGLE" / "step29_test_eval"
    out_dir.mkdir(parents=True, exist_ok=True)
    out = out_dir / "kaggle_step29_test_eval.ipynb"
    out.write_text(json.dumps(nb, indent=1), encoding="utf-8")
    print(f"wrote {out} ({len(nb['cells'])} cells, {out.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
