"""Stage C — generates KAGGLE/stage_c_tables/kaggle_stage_c_tables.ipynb from
scripts/run_finetune_tables.py.

Same self-contained-embed philosophy as scripts/build_kaggle_notebook.py (see that file's
own docstring): none of Stage C's dependencies are on `main` yet, so this notebook embeds
everything it needs rather than assuming a branch push. Two differences from Step 28's
notebook:

1. The starting checkpoint (`data/models/ocr_lora/curve_n122`, 6.9 MB) is too large to
   comfortably embed as base64 text -- uploaded instead as a private Kaggle Dataset
   (`eliasmainur/mathscholar-curve-n122-adapter`), the same "large -> Kaggle Dataset, not
   embedded" call `plan.md`'s Steps 25-28 handoff-risk note already establishes, mounted
   as a kernel input.
2. `data/annot/nist_tables/` (9 pairs, 533 KB, all PNGs) IS small enough to embed --
   base64-encoded inline, same reasoning `data/annot/nist/` was committed outright at
   Step 25 rather than sent through the Dataset path.

Regenerate after changing scripts/run_finetune_tables.py or any of its embedded
dependencies:
    python scripts/build_kaggle_notebook_stage_c.py
"""

from __future__ import annotations

import base64
import json
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
RUN_FINETUNE = (REPO_ROOT / "scripts" / "run_finetune.py").read_text(encoding="utf-8")
RUN_FINETUNE_TABLES = (REPO_ROOT / "scripts" / "run_finetune_tables.py").read_text(encoding="utf-8")
DATAMODULE = (REPO_ROOT / "src" / "doc_agent" / "training" / "datamodule.py").read_text(
    encoding="utf-8"
)
TRAIN_MODULE = (REPO_ROOT / "src" / "doc_agent" / "training" / "train.py").read_text(
    encoding="utf-8"
)
OCR_MODULE = (REPO_ROOT / "src" / "doc_agent" / "vision" / "ocr.py").read_text(encoding="utf-8")
TRAIN_CFG = (REPO_ROOT / "configs" / "train_ocr.yaml").read_text(encoding="utf-8")

NIST_TABLES_DIR = REPO_ROOT / "data" / "annot" / "nist_tables"
NIST_TABLES_PAIRS = (NIST_TABLES_DIR / "pairs.jsonl").read_text(encoding="utf-8")
NIST_TABLES_SUMMARY = (NIST_TABLES_DIR / "summary.json").read_text(encoding="utf-8")
NIST_TABLES_IMAGES: dict[str, str] = {
    p.name: base64.b64encode(p.read_bytes()).decode("ascii")
    for p in sorted((NIST_TABLES_DIR / "images").glob("*.png"))
}

ADAPTER_DATASET = "eliasmainur/mathscholar-curve-n122-adapter"


def md(src: str) -> dict:
    return {"cell_type": "markdown", "metadata": {}, "source": src.splitlines(keepends=True)}


def code(src: str) -> dict:
    return {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": src.splitlines(keepends=True),
    }


def build_cells() -> list[dict]:
    cells: list[dict] = []

    cells.append(md("""# MathScholar — Stage C: table-focused continuation fine-tune

Continues fine-tuning from the saved `curve_n122` adapter (Step 28's best checkpoint),
table-focused, per the direct request after Step 28's curve showed strong formula/prose
performance but hallucination on dense numeric tables (`as_p0509`, `as_p0351`).

Training data: 9 real NIST table pairs (embedded below) + 26 already-verified table-dense
A&S train pages (materialized via `ANNOT=1 get_data.sh`, same as every other GPU step).

**Catastrophic-forgetting guard**: writes to a NEW adapter directory
(`data/models/ocr_lora/table_ft/`), never overwrites `curve_n122`; low LR; early-stops on
the full 20-page A&S validation set, not a table-only subset; prints a per-page
before/after comparison so any regression is visible, not averaged away.

Generated by `scripts/build_kaggle_notebook_stage_c.py` from
`scripts/run_finetune_tables.py` — regenerate from there, don't hand-edit this file.
"""))

    cells.append(code(f"""REPO_URL = "https://github.com/anuronmaitro/doc-agent-1.git"
BRANCH = "main"
ADAPTER_DATASET_SLUG = "{ADAPTER_DATASET.split('/')[-1]}"
"""))

    cells.append(md("""## 1. Clone the repo and install pinned dependencies"""))
    cells.append(code("""import os
import subprocess

if not os.path.exists("/kaggle/working/repo"):
    subprocess.run(["git", "clone", "--branch", BRANCH, "--depth", "1", REPO_URL, "/kaggle/working/repo"], check=True)
%cd /kaggle/working/repo
!pip install -q --no-cache-dir -r requirements.lock
import pkg_resources  # noqa: F401

print("pkg_resources OK")
"""))

    cells.append(md("""## 2. Mount the starting checkpoint (curve_n122)

Attach the `mathscholar-curve-n122-adapter` dataset to this kernel (Add Input) before
running. Version 1 crashed here (`FileNotFoundError:
/kaggle/input/mathscholar-curve-n122-adapter`); version 2's fuzzy name-match on
`/kaggle/input/*` crashed too, because on this (papermill/batch-executed) kernel the
dataset is nested one level deeper than the interactive-notebook convention --
`/kaggle/input/` only contains a single `datasets` entry, with the real per-dataset folder
somewhere underneath it. Rather than guess a third exact path shape, this walks the whole
`/kaggle/input` tree and finds whichever directory actually contains `adapter_config.json`
-- the file that uniquely identifies the PEFT adapter's own contents -- so it's independent
of naming/nesting quirks entirely."""))
    cells.append(code("""import os
import shutil

print("Available /kaggle/input/ entries:", os.listdir("/kaggle/input"))
adapter_dir = None
for root, _dirs, files in os.walk("/kaggle/input"):
    if "adapter_config.json" in files:
        adapter_dir = root
        break
if adapter_dir is None:
    raise FileNotFoundError(
        "No directory under /kaggle/input contains adapter_config.json -- attach the "
        "'mathscholar-curve-n122-adapter' dataset to this kernel (Add Input) before "
        "running. Full tree: "
        f"{[(r, files) for r, _, files in os.walk('/kaggle/input')]}"
    )
src = adapter_dir
print(f"using {src}")
dst = "data/models/ocr_lora/curve_n122"
os.makedirs(dst, exist_ok=True)
shutil.copytree(src, dst, dirs_exist_ok=True)
print("copied", os.listdir(dst))
"""))

    cells.append(md("""## 3. Materialize the A&S page images (val + the 26 table-dense train pages)

Same `ANNOT=1 bash scripts/get_data.sh` every GPU step uses -- covers all 181 annotation
pages (val + train + test) in one pass, so this also materializes the 26 table-dense
train pages `run_finetune_tables.py` reuses, not just val."""))
    cells.append(code("""!ANNOT=1 bash scripts/get_data.sh
"""))

    cells.append(
        md("""## 4. Write the NIST table pairs (9 pairs, embedded -- small enough to inline, see
this notebook's own generator docstring for why it isn't a Dataset like the adapter).""")
    )
    img_lines = [
        "import base64",
        "import os",
        "",
        'os.makedirs("data/annot/nist_tables/images", exist_ok=True)',
    ]
    for name, b64 in NIST_TABLES_IMAGES.items():
        img_lines.append(
            f'open("data/annot/nist_tables/images/{name}", "wb").write(base64.b64decode("{b64}"))'
        )
    img_lines.append(
        "print(f\"wrote {len(os.listdir('data/annot/nist_tables/images'))} table images\")"
    )
    cells.append(code("\n".join(img_lines)))
    cells.append(code("%%writefile data/annot/nist_tables/pairs.jsonl\n" + NIST_TABLES_PAIRS))
    cells.append(code("%%writefile data/annot/nist_tables/summary.json\n" + NIST_TABLES_SUMMARY))

    cells.append(md("""## 5. Write the code (5 files -- run_finetune.py is imported by
run_finetune_tables.py for its shared eval/adapter helpers)."""))
    cells.append(
        code(
            'import os\n\nos.makedirs("src/doc_agent/training", exist_ok=True)\nos.makedirs("src/doc_agent/vision", exist_ok=True)\n'
        )
    )
    cells.append(code("%%writefile src/doc_agent/training/datamodule.py\n" + DATAMODULE))
    cells.append(code("%%writefile src/doc_agent/training/train.py\n" + TRAIN_MODULE))
    cells.append(code("%%writefile src/doc_agent/vision/ocr.py\n" + OCR_MODULE))
    cells.append(code("%%writefile configs/train_ocr.yaml\n" + TRAIN_CFG))
    cells.append(code("%%writefile scripts/run_finetune.py\n" + RUN_FINETUNE))
    cells.append(code("%%writefile scripts/run_finetune_tables.py\n" + RUN_FINETUNE_TABLES))

    cells.append(md("""## 6. Smoke-check, then the real run"""))
    cells.append(code("""!python scripts/run_finetune_tables.py --smoke
"""))
    cells.append(code("""!df -h /kaggle/working
!python scripts/run_finetune_tables.py
!df -h /kaggle/working
"""))

    cells.append(md("""## 7. Package the output for download"""))
    cells.append(code("""import shutil

out_dir = "/kaggle/working/out"
os.makedirs(out_dir, exist_ok=True)
shutil.copytree("data/models/ocr_lora/table_ft", f"{out_dir}/table_ft", dirs_exist_ok=True)
archive_path = shutil.make_archive("/kaggle/working/stage_c_output", "zip", out_dir)
print(f"wrote {archive_path} ({os.path.getsize(archive_path) / 1e6:.1f} MB)")
"""))

    return cells


def main() -> None:
    nb = {
        "cells": build_cells(),
        "metadata": {
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python", "version": "3.10"},
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }
    out = REPO_ROOT / "KAGGLE" / "stage_c_tables" / "kaggle_stage_c_tables.ipynb"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(nb, indent=1), encoding="utf-8")
    print(f"wrote {out} ({len(nb['cells'])} cells, {out.stat().st_size / 1e6:.2f} MB)")


if __name__ == "__main__":
    main()
